- name: Bouncy cursor apps
  kconfig:
    file: ~/.config/klaunchrc
    groups: [BusyCursorSettings]
    key: Bouncing
    value: "true"

- name: Faster animations
  kconfig:
    file: ~/.config/kdeglobals
    groups: [KDE]
    key: AnimationDurationFactor
    value: "0.5"

- name: Hide notifications faster
  kconfig:
    file: ~/.config/plasmanotifyrc
    groups: [Notifications]
    key: PopupTimeout
    value: "3000"

- name: Disable ScreenReader
  kconfig:
    file: ~/.config/kaccessrc
    groups: [ScreenReader]
    key: Enabled
    value: "false"

- name: Setup .face
  copy:
    src: /usr/share/plasma/avatars/photos/Astronaut.png
    dest: "{{ HOME }}/.face"
    mode: u=rw,g=rw,o=r
    force: false

- name: Create autostart directory
  file:
    state: directory
    path: "{{ HOME }}/.config/autostart"
    mode: u=rwx,go=rx

- name: KDE ssh-agent
  blockinfile:
    path: "{{ HOME }}/.profile"
    marker: "# {mark} kde ssh-agent"
    block: |
      export SSH_ASKPASS_REQUIRE=prefer
      export SSH_ASKPASS=/usr/bin/ksshaskpass

- name: Disable Plasma Browser Integration
  kconfig:
    file: ~/.config/kded5rc
    groups: [PlasmaBrowserIntegration]
    key: shownCount
    value: "100"
