- name: Setup Eternal Bash History
  blockinfile:
    path: "{{ HOME }}/.bashrc"
    insertafter: "# END Tilix Config"
    marker: "# {mark} Eternal Bash History"
    block: |
      # Undocumented feature which sets the size to "unlimited".
      # http://stackoverflow.com/questions/9457233/unlimited-bash-history
      export HISTFILESIZE=
      export HISTSIZE=
      export HISTTIMEFORMAT="[%F %T] "
      # Change the file location because certain bash sessions truncate .bash_history file upon close.
      # http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
      export HISTFILE=~/.bash_eternal_history
      # Force prompt to write history after every command.
      # http://superuser.com/questions/20900/bash-history-loss
      PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
      export HISTCONTROL=ignoreboth
      export HISTIGNORE="export AWS_ACCESS_KEY_ID=*:export AWS_SECRET_ACCESS_KEY=*:export AWS_SESSION_TOKEN=*"

- name: Enforce Eternal Bash History
  replace:
    path: "{{ HOME }}/.bashrc"
    regexp: '^(\s*)?(export\s+)?{{ item }}=.*$'
    replace: '\1\2{{ item }}='
  with_items:
    - HISTFILESIZE
    - HISTSIZE
