- name: Create $HOME/bin folder
  file:
    state: directory
    path: "{{ HOME }}/bin/"
    mode: u=wrx,go=rx

- name: Setup $PATH for $HOME/bin
  blockinfile:
    dest: "{{ HOME }}/.bashrc"
    marker: "# {mark} HomeBin"
    block: |
      export PATH="$PATH:$HOME/bin"

- name: Create git repos folder
  file:
    state: directory
    path: "{{ HOME }}/git/"
    mode: u=wrx,go=rx

- name: Symlink git repos folder
  file:
    state: link
    path: "{{ HOME }}/Documents/git"
    src: "{{ HOME }}/git/"
    mode: u=rwx,go=rx
