- import_tasks: as_user.yml
  become: true
  become_user: "{{ USER }}"

- name: Install zpcrypt
  copy:
    src: "{{ role_path }}/files/zpcrypt"
    dest: /usr/local/bin/zpcrypt
    mode: u=rwx,go=rx
