- name: Install Ripgrep config
  copy:
    dest: "{{ HOME }}/.ripgreprc"
    mode: u=rwx,g=rx,o=
    content: |
      # Don't let ripgrep vomit really long lines to my terminal, and show a preview.
      --max-columns=150
      --max-columns-preview

      # Because who cares about case!?
      --smart-case

      # follow symbolic links
      --follow

- name: Setup Ripgrep to use config
  blockinfile:
    path: "{{ HOME }}/.bashrc"
    marker: "# {mark} Ripgrep config"
    block: |
      export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"
