- name: Create a .secrets folder
  file:
    state: directory
    path: "{{ HOME }}/.secrets/"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: u=rwx,g=s,o=

- name: Limit home folder access
  file:
    state: directory
    path: "{{ HOME }}/"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: u=rwx,g=rx,o=
