#!/usr/bin/env bash
set -euo pipefail

GIT_FOLDER=~/git
REPO=https://github.com/ZeePal/workstation-ubuntu.git
REPO_NAME="$(basename -s .git "$REPO")"


sudo apt update
sudo apt install -y make ansible git

if [[ ! -e $GIT_FOLDER ]]; then
  mkdir -p "$GIT_FOLDER"
fi
cd "$GIT_FOLDER"
git clone "$REPO"

cd "$REPO_NAME"
exec make install
