#!/usr/bin/env bash
set -euo pipefail

GIT_FOLDER=~/git/ZeePal
REPO=https://github.com/ZeePal/workstation-kubuntu.git
REPO_NAME="$(basename -s .git "$REPO")"

sudo apt update
sudo apt install -y software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible

sudo apt install -y ansible git python3-apt curl build-essential

if [[ ! -e $GIT_FOLDER ]]; then
  mkdir -p "$GIT_FOLDER"
fi
cd "$GIT_FOLDER"
git clone "$REPO"

cd "$REPO_NAME"
./install >bootstrap_install.log 2>&1
reboot
