#!/usr/bin/env bash
set -euo pipefail
# Startup application command for testing:
## gnome-terminal -- /bin/bash -c '/mnt/test/dev_bootstrap_install;exec bash -i'

GIT_FOLDER=~/git
REPO=/mnt/test
REPO_NAME="$(basename -s .git "$REPO")"


sudo apt update
sudo apt install -y ansible git

if [[ ! -e $GIT_FOLDER ]]; then
  mkdir -p "$GIT_FOLDER"
fi
cd "$GIT_FOLDER"
rsync -a "$REPO/" "$GIT_FOLDER/$REPO_NAME/"

cd "$REPO_NAME"
exec ./install
