#!/usr/bin/env bash
set -euo pipefail

GIT_FOLDER=~/git/ZeePal
REPO=/mnt/test
REPO_NAME=workstation-kubuntu

sudo apt update
sudo apt install -y software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible

sudo apt install -y ansible git python3-apt curl build-essential

if [[ ! -e $GIT_FOLDER ]]; then
  mkdir -p "$GIT_FOLDER"
fi
cd "$GIT_FOLDER"
rsync -a "$REPO/" "$GIT_FOLDER/$REPO_NAME/"

cd "$REPO_NAME"
./install
reboot
