#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
WORK_WORKSTATION_MARKER="$HOME/.config/ZeePal/work"

if [ -f "$WORK_WORKSTATION_MARKER" ]; then
    export ZP_WORKSTATION=work
else
    export ZP_WORKSTATION=personal
fi

sudo --preserve-env=ZP_TEST_MODE,ZP_WORKSTATION "$SCRIPT_DIR/scripts/run_ansible_roles_in_parallel" \
    --user "$USER" \
    --uid "$UID" \
    --home "$HOME" \
    "$@"
