#!/usr/bin/env python3
from collections import namedtuple
from subprocess import Popen
import shlex
import os
from time import time
import argparse
import queue
from signal import signal, SIGCHLD

SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
ROLES_DIR = f"{SCRIPT_DIR}/roles"
SLEEP_INTERVAL = 10

Roles = namedtuple("Roles", ["child_to_parents", "parent_to_children"])


# Catch all SIGCHLD's and store the related child details
SIGCHLD_QUEUE = queue.Queue()
signal(SIGCHLD, lambda x, y: SIGCHLD_QUEUE.put(os.waitpid(-1, os.WNOHANG)))


def main():
    args = get_args()
    if not args.role:
        # Build real dep tree from all roles
        roles = build_dep_tree()
    else:
        # Build fake dep tree using provided roles
        r = {role: set() for role in args.role}
        roles = Roles(r, r)
    run_roles(
        roles, args.username, check=args.check, ignore_errors=args.ignore_errors,
    )


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-u",
        "--username",
        help="What is the username of the primary workstation user?",
        required=True,
        type=str,
    )
    parser.add_argument(
        "role", help="Roles to execute (Default is all)", nargs="*", type=str
    )
    parser.add_argument(
        "-e",
        "--exclude",
        help="Roles to exclude",
        action="append",
        default=[],
        type=str,
    )
    parser.add_argument("-c", "--check", help="Check only", action="store_true")
    parser.add_argument(
        "-i",
        "--ignore-errors",
        help="Continue executing if errors occur",
        action="store_true",
    )
    return parser.parse_args()


def build_dep_tree():
    child_to_parents = load_role_dependencies()
    parent_to_children = get_role_dependants(child_to_parents)
    return Roles(child_to_parents, parent_to_children)


def load_role_dependencies():
    output = {}
    for role in os.scandir(ROLES_DIR):
        if role.is_dir():
            try:
                with open(f"{role.path}/depends_on", "r") as f:
                    # 1 line = 1 dependancy, whole line is a role name
                    output[role.name] = set(f.read().splitlines())
            except FileNotFoundError:
                # Missing file equiv to empty depends_on list
                output[role.name] = set()
    return output


def get_role_dependants(child_to_parents):
    output = {role: set() for role in child_to_parents.keys()}
    for child, parents in child_to_parents.items():
        for parent in parents:
            try:
                output[parent].add(child)
            except KeyError:
                raise ValueError(
                    f"Role '{child}' depends on non-existant role '{parent}'"
                )
    return output


class RoleError(Exception):
    pass


def run_roles(roles, user, check=False, ignore_errors=False):
    errors = []
    running = {}
    while running or (roles.child_to_parents and (not errors or ignore_errors)):
        if not errors or ignore_errors:
            start_ready_roles(running, roles, user, check)
        else:
            print("\n\n##### Errors Detected, not starting any more roles ######\n\n")

        wait_for_role_to_finish(running, roles, errors)
    if errors and not ignore_errors:
        raise RoleError(", ".join(errors))


def wait_for_role_to_finish(running, roles, errors):
    waiting_on = ", ".join([proc["role"] for proc in running.values()])
    print(f"Waiting on: {waiting_on}")
    try:
        # Wait for a SIGCHLD
        pid, exit_code = SIGCHLD_QUEUE.get(timeout=SLEEP_INTERVAL)
        if pid == 0:  # Failed to get which child died
            poll_running_roles(running, roles, errors)  # Check them all
            return

        process_finished_role(running, roles, pid, exit_code, errors)
        try:
            # Empty the queue incase we received more signals
            while True:
                pid, exit_code = SIGCHLD_QUEUE.get_nowait()
                process_finished_role(running, roles, pid, exit_code, errors)
        except queue.Empty:
            pass  # Queue has been emptied
    except queue.Empty:
        # Timeout used as a sleep. Safety check incase a signal was missed.
        poll_running_roles(running, roles, errors)  # Check them all


def start_ready_roles(running, roles, primary_username, check):
    for child in list(roles.child_to_parents.keys()):
        if not roles.child_to_parents[child]:
            # If no dependancys left
            proc = start_ansible(child, primary_username, check=check)
            running[proc.pid] = {"role": child, "proc": proc, "start": time()}
            del roles.child_to_parents[child]
    if not running:
        raise RoleError(f"Circular dependancy detected: {roles.child_to_parents}")


def process_finished_role(running, roles, pid, exit_code, errors):
    proc = running[pid]
    parent = proc["role"]
    print(f"Role {parent}: Elapsed {time()-proc['start']}")
    print(f"Role {parent}: Exit Code {exit_code}")

    if exit_code != 0:
        errors.append(f"Role '{parent}' exited with status code: {exit_code}")

    for child in roles.parent_to_children.get(parent, []):
        roles.child_to_parents[child].remove(parent)
    del running[pid]


# Failsafe function
def poll_running_roles(running, roles, errors):
    for pid in list(running.keys()):
        exit_code = running[pid]["proc"].poll()
        if exit_code is not None:
            process_finished_role(running, roles, pid, exit_code, errors)


def start_ansible(role, primary_username, check=False):
    print(f"Starting Role: {role}")
    safe_role = shlex.quote(role)
    safe_primary_username = shlex.quote(primary_username)

    cmd = ["ansible localhost"]
    if check:
        cmd.append("-CD")
    cmd.extend(
        [
            "-m include_role",
            f"-a name={safe_role}",
            f"-e primary_username={safe_primary_username}",
            "-e ansible_python_interpreter=/usr/bin/python3",
            # Add output prefix's
            "2>&1|awk -W interactive",
            f"-v role={safe_role}",
            '\'{print strftime("%Y-%m-%d %H:%M:%S")": "role": "$0}\'',
            ";exit ${PIPESTATUS[0]}",  # Pass correct exit code back
        ]
    )
    return Popen(" ".join(cmd), shell=True, executable="/bin/bash", cwd=SCRIPT_DIR)


if __name__ == "__main__":
    main()
