- import_tasks: theme.yml
  become: true
  become_user: "{{ primary_username }}"
- import_tasks: dock.yml
  become: true
  become_user: "{{ primary_username }}"
- import_tasks: misc.yml
  become: true
  become_user: "{{ primary_username }}"
- import_tasks: meld.yml
  become: true
  become_user: "{{ primary_username }}"

- include: mouse.yml

- include: gnome_extensions/main.yml

- include: fix_virtualbox_icon.yml
