- name: Configure Delta to be used by git
  blockinfile:
    path: "{{ HOME }}/.gitconfig"
    marker: "# {mark} delta"
    create: true
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: u=rw,go=r
    block: |
      [core]
          pager = delta
          editor = nvim

      [interactive]
          diffFilter = delta --color-only

      [delta]
          theme = TwoDark
          side-by-side = true
          navigate = true

      [merge]
          conflictstyle = diff3

      [diff]
          colorMoved = default
          tool = meld
