- name: Check for recent tldr cache updates
  find:
    paths: "{{ HOME }}/.cache/tealdeer/tldr-pages/"
    patterns: "index.json"
    age: -12h
  register: tldr_cache_last_update

- name: Update tldr cache
  become: true
  become_user: "{{ USER }}"
  command: "{{ HOME }}/.cargo/bin/tldr --update"
  when: not tldr_cache_last_update.files # If not recently updated
