- name: No Mouse Accel
  copy:
    dest: /usr/share/X11/xorg.conf.d/50-mouse-acceleration.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    content: |
      Section "InputClass"
        Identifier "My Mouse"
        Driver "libinput"
        MatchIsPointer "yes"
        Option "AccelProfile" "flat"
        Option "AccelSpeed" "0"
      EndSection
