- name: Install apt packages
  apt:
    state: present
    name:
      - curl
      - wget
      - ansible
      - ent
      - jq
      - yq
      - fzf
      - google-chrome-stable
      - git
      - meld
      - python3-pip
      - pipx
      - python3-bs4
      - python3-boto3
      - python3-botocore
      - python3-cryptography
      - python3-pylsp
      - python3-requests
      - python3-yaml
      - python3-jmespath
      - shellcheck
      - pwgen
      - sysstat
      - zip
      - unzip
      - vlock
      - rsync
      - build-essential
      - apt-file
      - software-properties-common
      - ppa-purge
      - powertop
      - tlp
      - tlp-rdw
      - gpg
      - golang-go
      - uidmap
      - dconf-editor
      - gparted
      - handbrake
      - gimp
      - neofetch
      - kdenlive
      - virtualbox
      - inotify-tools
      - lm-sensors
      - mesa-utils
      - pigz
      - p7zip-full
      - iotop
      - iftop
      - graphviz
      - dos2unix
      - whois
      - geoip-bin
      - remmina
      - binutils-x86-64-linux-gnu
      - libssl-dev
      - vlc
      - ripgrep
      - htop
      - sqlformat
      - traceroute
      - oathtool
      - screenfetch
      - signal-desktop
      - net-tools
      - pv
      - moreutils
      - dconf-cli
      - filelight
      - sqlite3
      - python3-venv
      - google-cloud-cli
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-ce-rootless-extras
      - docker-compose-plugin
      - bat
      - terraform
      - parallel
      - iperf3
      - gnome-keyring
      - seahorse
      - speedcrunch
      - kio-gdrive
      - aptitude
      - cloud-image-utils
      - cmake
      - alacritty
      - tmux
      - nodejs
      - shfmt
      - granted
      - gh
      - pylint
      - black
      - isort

      # KDE Notification Language Support
      - gimp-help-en
      - gimp-help-en-gb
      - hunspell-en-au
      - hunspell-en-ca
      - hunspell-en-gb
      - hunspell-en-za
