- name: Install apt packages
  apt:
    state: present
    name:
      - curl
      - wget
      - ansible
      - ansible-lint
      - python-setuptools
      - ent
      - jq
      - fzf
      - google-chrome-stable
      - git
      - meld
      - python3-pip
      - shellcheck
      - tilix
      - pwgen
      - sysstat
      - zip
      - unzip
      - vim
      - vlock
      - rsync
      - build-essential
      - apt-file
      - software-properties-common
      - ppa-purge
      - powertop
      - tlp
      - tlp-rdw
      - gpg
      - golang-go
      - uidmap
      - dconf-editor
      - gparted
      - handbrake
      - gimp
      - neofetch
      - kdenlive
      - virtualbox
      - inotify-tools
      - lm-sensors
      - mesa-utils
      - pigz
      - p7zip-full
      - iotop
      - iftop
      - graphviz
      - dos2unix
      - whois
      - geoip-bin
      - remmina
      - binutils-x86-64-linux-gnu
      - libssl-dev
      - vlc
      - ripgrep
      - htop
      - sqlformat
      - traceroute
      - oathtool
      - screenfetch
      - signal-desktop
      - net-tools
      - pv
      - moreutils
      - dconf-cli
      - filelight
      - sqlite3
      - python3-venv
      - google-cloud-sdk
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-ce-rootless-extras
      - bat
      - terraform
      - parallel
      - code # VSCode
      - iperf3
      - gnome-keyring
      - seahorse
      - speedcrunch
      - kio-gdrive
      - aptitude
