- name: Configure apt to use a local mirror
  replace:
    path: /etc/apt/sources.list
    regexp: 'http://([^/ ]+\.)?archive.ubuntu.com/ubuntu/'
    replace: "{{ apt['mirror'] }}"
  notify: Refresh apt
