- name: Create AWS cli install folders
  file:
    state: directory
    path: /opt/aws/cli/
    mode: u=rwX,go=rX

- name: Download AWS cli gpg key
  shell:
    cmd: |
      curl https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html \
        |sed -r -n '/-----BEGIN PGP PUBLIC KEY BLOCK-----/,/-----END PGP PUBLIC KEY BLOCK-----/p' \
        |sed -r 's/^.*(-----BEGIN PGP PUBLIC KEY BLOCK-----)/\1/;s/(-----END PGP PUBLIC KEY BLOCK-----).*$/\1/' > /opt/aws/cli/awscli.gpg.asc
    creates: /opt/aws/cli/awscli.gpg

- name: Get AWS cli gpg key hash
  stat:
    path: /opt/aws/cli/awscli.gpg.asc
    get_checksum: true
    checksum_algorithm: sha512
  register: awscli_gpg_key_hash

- name: Verify AWS cli gpg key hash
  when: awscli_gpg_key_hash.stat.checksum != 'd1db2601687fca3c9548af229a7abd5d8fa0144378deb0d9f22e53ba3b54957df351aa2e31bceebdaea69b847ebfb4a1e769c59e329ee99d885653d0b7eb8b35'
  fail:
    msg: AWS cli gpg key hash doesnt match the expected hash

- name: Build AWS cli gpg keyring
  command:
    cmd: |
      gpg --no-default-keyring --keyring /opt/aws/cli/awscli.gpg --import /opt/aws/cli/awscli.gpg.asc
    creates: /opt/aws/cli/awscli.gpg
