- name: Install VSCode extensions
  become: true
  become_user: "{{ USER }}"
  vscode_extensions:
    name:
      - foxundermoon.shell-format
      - kddejong.vscode-cfn-lint
      - timonwong.shellcheck
      - samuelcolvin.jinjahtml
      - rust-lang.rust-analyzer
      - ms-azuretools.vscode-docker
      - redhat.vscode-yaml
      - redhat.ansible
      - golang.Go
      - streetsidesoftware.code-spell-checker
      - TabNine.tabnine-vscode
      - oderwat.indent-rainbow
      - KevinRose.vsc-python-indent
      - Gruntfuggly.todo-tree
      - mechatroner.rainbow-csv
      - HashiCorp.terraform
      - ms-python.python
      - PKief.material-icon-theme
      - equinusocio.vsc-community-material-theme
      - equinusocio.vsc-material-theme
      - equinusocio.vsc-material-theme-icons
      - DavidAnson.vscode-markdownlint
      - tintinweb.graphviz-interactive-preview
