- name: Install pip packages
  pip:
    state: present
    executable: pip3
    name:
      - yq
      - beautifulsoup4
      - black
      - boto3
      - botocore
      - python-lsp-server[all]
      - pycryptodome
      - requests
      - pyyaml
      - thefuck
      - asciinema
      - docker-compose
      - cson
      - flake8
      - pyflakes
      - pycodestyle
      - cfn-lint
      - beautysh
      - pwntools
      - inotify
