#!/usr/bin/env python3
import re
import glob
import os
import sys

blank_or_comment_line = re.compile(r'^\s*(#.*)?$')

def is_blank_file(filename):
  with open(filename, "r") as file:
    for line in file:
      if not blank_or_comment_line.match(line):
        return False
  return True


for filename in glob.iglob('./**', recursive=True):
  if os.path.isfile(filename):
    if is_blank_file(filename):
      print(filename)
