- name: Install Git-Secrets Script
  get_url:
    url: https://raw.githubusercontent.com/awslabs/git-secrets/master/git-secrets
    dest: /usr/local/bin/git-secrets
    # no updates in ~7months
    checksum: sha512:65068d775925265200a279714618f7c03cad25870a78cc805a6178b533b3bfec4c4e45af8cf6e74dd8795ff5381f2dc82508c4e15293354ae2fc3def2665e654
    mode: u=rwx,go=rx
