# Preventing chrome from trying to manage the apt repo config for its self
- name: Create empty google-chrome config if missing
  copy:
    dest: /etc/default/google-chrome
    owner: root
    group: root
    mode: u=rw,go=r
    force: false
    content: ""

- name: Install the Google Chrome apt repository key
  apt_key:
    state: present
    keyring: /etc/apt/keyrings/google-chrome.gpg
    id: EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796
    url: https://dl.google.com/linux/linux_signing_key.pub

- name: Install restrictions for Google Chrome apt repo
  copy:
    dest: /etc/apt/preferences.d/50-google-chrome
    owner: root
    group: root
    mode: u=rw,go=r
    content: |
      Package: *
      Pin: origin dl.google.com
      Pin-Priority: 100

- name: Install the Google Chrome apt repository
  apt_repository:
    state: present
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome # As chrome manages its own repo list
    update_cache: false
  notify: Refresh apt
