- name: Create third party apt keyrings folder
  file:
    state: directory
    path: /etc/apt/keyrings
    owner: root
    group: root
    mode: u=rwx,go=rx

- import_tasks: google-chrome.yml
- import_tasks: google-cloud.yml
- import_tasks: signal.yml
- import_tasks: docker.yml
- import_tasks: hashicorp.yml
- import_tasks: vscode.yml
- import_tasks: alacritty.yml
