- name: Install the VSCode apt key
  apt_key:
    state: present
    keyring: /etc/apt/keyrings/vscode.gpg
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: https://packages.microsoft.com/keys/microsoft.asc


- name: Install restrictions for VSCode apt repo
  copy:
    dest: /etc/apt/preferences.d/50-vscode
    owner: root
    group: root
    mode: u=rw,go=r
    content: |
      Package: *
      Pin: origin packages.microsoft.com
      Pin-Priority: 100


- name: Install the VSCode apt repository
  apt_repository:
    state: present
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/vscode.gpg] https://packages.microsoft.com/repos/code stable main
    filename: vscode  # "code" package trys to manage this file
    update_cache: no
  notify: Refresh apt
