kde:
  favorites:
    task_bar:
      - preferred://filemanager
      - preferred://browser
      - applications:com.mitchellh.ghostty.desktop
    start_menu:
      - applications:signal-desktop.desktop
      - applications:org.kde.plasma-systemmonitor.desktop
      - applications:systemsettings.desktop
