- name: Install pre-commit into Git Template Folder
  command:
    cmd: pre-commit init-templatedir "{{ HOME }}/.config/git/templatedir" --config "{{ HOME }}/.config/git/pre-commit-config.yaml"
    creates: "{{ HOME }}/.config/git/templatedir/hooks/pre-commit"
