- name: Configure Meld as the difftool for git
  blockinfile:
    path: "{{ HOME }}/.gitconfig"
    marker: "# {mark} meld"
    create: true
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: u=rw,go=r
    block: |
      [difftool]
          prompt = false
      [difftool "meld"]
          cmd = meld "$LOCAL" "$REMOTE"

- name: Configure GPG signing
  blockinfile:
    path: "{{ HOME }}/.gitconfig"
    marker: "# {mark} gpg"
    create: true
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: u=rw,go=r
    block: |
      [commit]
        gpgsign = true
      [tag]
        gpgsign = true

- name: Git config folder
  file:
    state: directory
    path: "{{ HOME }}/.config/git"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: u=wrx,go=rx

- name: Fallback .gitignore
  copy:
    src: "{{ role_path }}/files/ignore"
    dest: "{{ HOME }}/.config/git/ignore"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: u=rwx,go=rx
