- name: Symlink vte
  file:
    state: link
    path: /etc/profile.d/vte.sh
    src: /etc/profile.d/vte-2.91.sh
    owner: root
    group: root
    mode: u=rwx,go=rx

- name: Set Tilix as default Terminal, part 1
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/tilix.wrapper
