#!/usr/bin/env bash
set -euo pipefail

GIT_FOLDER=~/git/ZeePal
REPO=https://github.com/ZeePal/workstation-kubuntu.git
REPO_NAME="$(basename -s .git "$REPO")"

echo "Installing install dependencys..."
sudo apt update
sudo apt install -y software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible

sudo apt install -y ansible git python3-apt curl build-essential

echo "Cloning Source Git Repo..."
mkdir -p "$GIT_FOLDER"
cd "$GIT_FOLDER"
git clone "$REPO"

echo "Starting full install..."
cd "$REPO_NAME"
/usr/bin/time --verbose --output bootstrap_install.timings ./install 2>&1 | tee bootstrap_install.log
reboot
