- name: Create Alacritty config folder
  file:
    state: directory
    path: "{{ HOME }}/.config/alacritty/"
    mode: u=wrx,go=rx

- name: Copy in Alacritty config
  copy:
    src: "{{ role_path }}/files/alacritty.toml"
    dest: "{{ HOME }}/.config/alacritty/alacritty.toml"
    mode: u=rw,go=r

- name: Set Alacritty as default Terminal, part 2
  become: true
  become_user: "{{ USER }}"
  kconfig:
    groups: [General]
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    TerminalApplication: alacritty
    TerminalService: Alacritty.desktop

- name: Get CtrlAltR shortcut config
  kconfig:
    file: ~/.config/kglobalshortcutsrc
    groups: [plasmashell]
    key: repeat_action
  register: kde_ctrl_alt_r

- name: Remove CtrlAltR shortcut conflict
  kconfig:
    file: ~/.config/kglobalshortcutsrc
    groups: [plasmashell]
    key: repeat_action
    value: "none,{{ kde_ctrl_alt_r.value.split(',', 1)[1] }}"

- name: Remove CtrlAltT shortcut conflict
  kconfig:
    file: ~/.config/kglobalshortcutsrc
    groups: [org.kde.konsole.desktop]
    key: _launch
    value: none,Ctrl+Alt+T,Konsole

- name: Update CtrlAltT to Alacritty
  kconfig:
    file: ~/.config/kglobalshortcutsrc
    groups: [Alacritty.desktop]
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    New: none,none,New Terminal
    _k_friendly_name: Alacritty
    _launch: Ctrl+Alt+T,none,Alacritty
