- name: Create Alacritty config folder
  file:
    state: directory
    path: "{{ HOME }}/.config/alacritty/"
    mode: u=wrx,go=rx

- name: Copy in Alacritty config
  copy:
    src: "{{ role_path }}/files/alacritty.toml"
    dest: "{{ HOME }}/.config/alacritty/alacritty.toml"
    mode: u=rw,go=r

- name: Set Alacritty as default Terminal, part 2
  become: true
  become_user: "{{ USER }}"
  kconfig:
    groups: [General]
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    TerminalApplication: alacritty
    TerminalService: com.alacritty.Alacritty.desktop

- name: Get CtrlAltR shortcut config
  kconfig:
    file: ~/.config/kglobalshortcutsrc
    groups: [plasmashell]
    key: repeat_action
  register: kde_ctrl_alt_r

- name: Remove CtrlAltR shortcut conflict
  kconfig:
    file: ~/.config/kglobalshortcutsrc
    groups: [plasmashell]
    key: repeat_action
    value: "none,{{ kde_ctrl_alt_r.value.split(',', 1)[1] }}"

- name: Update CtrlAltT to Alacritty
  replace:
    path: "{{ HOME }}/.config/khotkeysrc"
    regexp: "{{ item.key }}"
    replace: "{{ item.value }}"
  with_dict:
    Name=Launch Konsole: Name=Launch Alacritty
    CommandURL=org\.kde\.konsole\.desktop: CommandURL=com.alacritty.Alacritty.desktop
    Name=Run Konsole: Name=Run Alacritty
    CommandURL=konsole: CommandURL=alacritty
