- name: Setup gcd command alias
  blockinfile:
    path: "{{ HOME }}/.bash_aliases"
    marker: "# {mark} gcd"
    create: true
    mode: u=rw,go=r
    block: |
      function _gcd { CDPATH={{ HOME }}/git/ _simpler_cd_completer "$@"; }
      complete -o nospace -F _gcd gcd
      function gcd { cd "{{ HOME }}/git/$1"; }
