- name: Setup Misc command aliases
  blockinfile:
    path: "{{ HOME }}/.bash_aliases"
    marker: "# {mark} Misc"
    create: true
    mode: u=rw,go=r
    block: !unsafe |
      alias o=xdg-open
      alias open=xdg-open
      alias rga='rg -uuu'
      alias l='exa'
      alias ll='exa -al'
      alias pw='pwgen -cnys1 32 1'
      alias pws='pwgen -cns1 32 1'
      alias table="column -t"

      function jat() { jq . "${1:--}" |bat -l json; }
      alias p=parallel
      alias pxargs='parallel -X --group'

      complete -o nospace -F _fzf_dir_completion mcd
      function mcd { mkdir -p "$1" && cd "$1"; }
