- name: Setup tcd command alias
  blockinfile:
    path: "{{ HOME }}/.bash_aliases"
    marker: "# {mark} tcd"
    create: true
    mode: u=rw,go=r
    block: !unsafe |
      function _tcd { CDPATH=/tmp/phtest/ _simpler_cd_completer "$@"; }
      complete -o nospace -F _tcd tcd
      function tcd { local folder="/tmp/phtest/$1";[ -d "$folder" ] || mkdir -p "$folder"; cd "$folder"; }
