- name: Bootstrap NeoVim Package Managers/Installers
  command:
    cmd: nvim --headless '+Lazy! restore' '+TSUpdateSync' +qa && nvim --headless '+Lazy! restore' '+TSUpdateSync' +qa
    creates: "{{ HOME }}/.local/share/nvim/lazy/lazy.nvim"
  register: init_bootstrap_neovim

- name: Try and Install at least some of the Mason Packages from ensure_installed's
  when: init_bootstrap_neovim.changed
  command:
    cmd: nvim /tmp/test.py
  async: 3600
  poll: 0  # nohup, as its bootstrapping, we will reboot soon
