- name: Bat symlink
  file:
    state: link
    path: /usr/local/bin/bat
    src: /usr/bin/batcat
    owner: root
    group: root
    mode: u=rwx,go=rx

- import_tasks: as_user.yml
  become: true
  become_user: "{{ USER }}"
