- name: Create pi-sandbox repo parent folder
  file:
    state: directory
    path: "{{ HOME }}/git/ZeePal/"
    mode: ug=wrx,o=rx

- name: Check if pi-sandbox repository already exists
  stat:
    path: "{{ HOME }}/git/ZeePal/pi-sandbox/.git"
  register: stat_pi_sandbox_repo

- name: Clone pi-sandbox repository
  git:
    repo: https://github.com/ZeePal/pi-sandbox.git
    dest: "{{ HOME }}/git/ZeePal/pi-sandbox"
    clone: true
    update: false
  when: not stat_pi_sandbox_repo.stat.exists

- name: Get pi-sandbox origin URL
  command: git -C "{{ HOME }}/git/ZeePal/pi-sandbox" remote get-url origin
  register: pi_sandbox_origin_url
  changed_when: false

- name: Switch pi-sandbox origin to SSH
  command: git -C "{{ HOME }}/git/ZeePal/pi-sandbox" remote set-url origin git@github.com:ZeePal/pi-sandbox.git
  when: pi_sandbox_origin_url.stdout != 'git@github.com:ZeePal/pi-sandbox.git'

- name: Install pi-sandbox
  command: "{{ HOME }}/.cargo/bin/cargo install --locked --path {{ HOME }}/git/ZeePal/pi-sandbox"
  args:
    creates: "{{ HOME }}/.cargo/bin/pi-sandbox"
